version: "3.3"

services:
  frontend:
    image: intkbv/bonnefanten-frontend:sha-62d2a7c
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    depends_on:
      - backend
    networks:
      - nw-data
    ports:
      - 3000:3000
    deploy:
      replicas: 2

  backend:
    image: intkbv/bonnefanten-backend:sha-566a56f
    environment:
      ZEO_ADDRESS: zeo:8100
      SITE: Plone
      DOCKER_DEPLOYMENT: "true"
    volumes:
      - /var/local/bonnefanten:/app/logs
      - /var/local/bonnefanten/import:/app/import
    env_file:
      - ../container.env
    networks:
      - nw-data
    ports:
      - 8080:8080
    deploy:
      replicas: 2
    depends_on:
      - zeo

  zeo:
    image: plone/plone-zeo:latest
    # ports:
    # - 8100:8100
    volumes:
      - /var/local/bonnefanten/data:/data
    networks:
      - nw-data

  conversion:
    image: plone/blocks-conversion-tool:latest
    ports:
      - 5000:5000
    networks:
      - nw-data

networks:
  nw-data:
    driver: overlay
